FROM python:3.11-slim

WORKDIR /app

# Install dependencies
RUN apt-get update && apt-get install -y \
    curl \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install -r requirements.txt

# Copy application code
COPY app/ ./app/
COPY simulator/ ./simulator/

# Create non-root user
RUN useradd -m -u 1000 simulator && \
    chown -R simulator:simulator /app

USER simulator

# Run simulator
CMD ["python","-u", "simulator/simulator.py"]
